name: CI Pipeline - Build Docker Image Locally

on:
  push:
    branches: [main]

jobs:
  build_complie:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install flake8

    - name: Lint Python code
      run: |
        flake8 src/app.py
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y
        
    - name: Scan source code and IaC with Trivy
      run: trivy config --exit-code 1 --severity HIGH,CRITICAL .

        
    - name: Run Python app
      run: |
        python src/app.py &
        sleep 5
        
    - name: Build Docker image
      run: |
        docker build -t hello-world-app .

    - name: Verify Docker image created
      run: |
        docker images | grep hello-world-app

    # Save Docker image to local folder
    - name: Save Docker image to folder
      run: |
        mkdir -p docker-images
        docker save hello-world-app > docker-images/hello-world-app.tar
        
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3.1.3
      with:
       name: hello-world-docker-image
       path: docker-images/hello-world-app.tar

     
