name: CI Pipeline - Build Docker Image Locally

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
    - name: Run Python app
      run: |
        python src/app.py &
        sleep 5
        # You can add curl or other tests here if needed
    - name: Build Docker image
      run: |
        docker build -t hello-world-app .

    - name: Verify Docker image created
      run: |
        docker images | grep hello-world-app

     
