name: CI Pipeline - Build Docker Image Locally

on:
  push:
    branches: [main]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

  code_quality:
    runs-on: ubuntu-latest
    steps:  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install flake8

    - name: Lint Python code
      run: |
        flake8 src/app.py

    - name: Run Python app
      run: |
        python src/app.py &
        sleep 5

  build_image:
   runs-on: ubuntu-latest

   steps:
    - name: Build Docker image
      run: |
        docker build -t hello-world-app:latest .

    - name: Verify Docker image created
      run: |
        docker images | grep hello-world-app
        

    # Save Docker image to local folder
    - name: Save Docker image to folder
      run: |
        mkdir -p docker-images
        docker save hello-world-app > docker-images/hello-world-app.tar
        
    

     
