name: CI Pipeline - Build Docker Image Locally

on:
  push:
    branches: [main]

jobs:
  checkout:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install flake8

    - name: Lint Python code
      run: |
        flake8 src/app.py

    - name: Run Python app
      run: |
        python src/app.py &
        sleep 5

    - name: Build Docker image
      run: |
        docker build -t hello-world-app:latest .

    - name: Verify Docker image created
      run: |
        docker images | grep hello-world-app
        

    # Save Docker image to local folder
    - name: Save Docker image to folder
      run: |
        mkdir -p docker-images
        docker save hello-world-app > docker-images/hello-world-app.tar
        
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
         name: hello-world-app
         path: docker-images/hello-world-app.tar
        
    

     
